### PR TITLE
Add args to triggers

### PR DESCRIPTION
**Pull request by golgote**
Small change to add args to triggers. Does it work for you ?

### CODE REVIEW

**Comment by eugwne** [comment]
Works for me. What about test for this case? 
I see that for trigger like :

``` SQL
CREATE TRIGGER test_trigger
  AFTER INSERT
  ON sometable
  FOR EACH ROW
  EXECUTE PROCEDURE test_function("hello");
```

what worked before changes:

``` sql
CREATE OR REPLACE FUNCTION test_function() RETURNS trigger AS $$
  print(select(1,...))
$$ LANGUAGE pllua 
```

should be changed to :

``` sql
CREATE OR REPLACE FUNCTION test_function() RETURNS trigger AS $$
  print(trigger.args[0])
$$ LANGUAGE pllua 
```

**Comment by golgote** [comment]
Maybe we could keep both ways. Using args is more compatible with other PL and with Postgresql documentation. But select() is more lua-ish.
I also have to test with null values to see how it goes.

**Comment by golgote** [comment]
Arguments only support literal strings so no nil values problems, at least.

**Comment by golgote** [comment]
I am closing it since it is not really necessary.

**Pull request closed without merging**
